# http://module-build.sourceforge.net/META-spec.html
name:         ExtUtils-MY_Metafile
version:      0.09
version_from: lib/ExtUtils/MY_Metafile.pm
installdirs:  site
author:       YAMASHINA Hio <hio@cpan.org>
abstract:     META.yml customize with ExtUtil::MakeMaker
license:      perl
requires:
  ExtUtils::MakeMaker: 0
build_requires:
  Test::Exception: 0
  Test::More:      0
no_index:
  directory:
    - example
    - t

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.09, EUMM-6.17.
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
