# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ExtUtils-MY_Metafile
version:      0.02
version_from: lib/ExtUtils/MY_Metafile.pm
installdirs:  site
author:       YAMASHINA Hio <hio@cpan.org>
abstract: META.yml customize with ExtUtil::MakeMaker
requires:
    Test::More:                    0
no_index:
  directory:
    - example
    - t
license: perl

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.02
meta-spec:
  version: 1.2
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
